info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - index
  /user/GetUserList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - getlist
swagger: "2.0"
