info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /searchFriends:
    post:
      parameters:
      - description: Id of the user
        in: query
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: search friends
      tags:
      - searchfriends
  /user/DeleteUser:
    delete:
      parameters:
      - description: Name of the user
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete a user
      tags:
      - DeleteUser
  /user/GetUserList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - getlist
  /user/Login:
    post:
      parameters:
      - description: Email of the user
        in: query
        name: email
        required: true
        type: string
      - description: Password of the user
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: User login
      tags:
      - Login
  /user/Register:
    post:
      parameters:
      - description: Email of the user
        in: query
        name: email
        required: true
        type: string
      - description: Name of the user
        in: query
        name: name
        required: true
        type: string
      - description: Password of the user
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Register a new user
      tags:
      - register
  /user/UpdateUser:
    put:
      parameters:
      - description: ID of the user
        in: query
        name: id
        required: true
        type: string
      - description: Name of the user
        in: query
        name: name
        required: true
        type: string
      - description: Email of the user
        in: query
        name: email
        required: true
        type: string
      - description: Password of the user
        in: query
        name: password
        required: true
        type: string
      - description: Phone of the user
        in: query
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update a user
      tags:
      - UpdateUser
swagger: "2.0"
